server:
  port: 8070

eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 90 # 过期踢出时间，默认90S
    lease-renewal-interval-in-seconds: 30 # 心跳检测，间隔一段时间向服务端发送心跳，证明存活，默认30
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: route

  cloud:
    gateway:
      routes:
        - id: server1
          # lb代表从注册中心获取服务
          uri: lb://server1
          predicates:
            # 转发对外的路径,即: curl http://localhost:8080/hello 实际访问的是内部lb://xc-zookeeper-client/获取的服务
            - Path=/server1/**
          filters:
            # 注意,这个地方是去除前缀,否则会带上/hello去访问注册中心的服务
            - StripPrefix=1