server:
  port: 8081

eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 90 # 过期踢出时间，默认90S
    lease-renewal-interval-in-seconds: 30 # 心跳检测，间隔一段时间向服务端发送心跳，证明存活，默认30
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: server1

  cloud:
    gateway:
      routes:
        - id: home
          # lb代表从注册中心获取服务
          uri: http://localhost:1323
          predicates:
            # 转发对外的路径,即: curl http://localhost:8080/hello 实际访问的是内部lb://xc-zookeeper-client/获取的服务
            - Path=/**
