server:
  port: 8888

spring:
  config:
    use-legacy-processing: false # Spring Boot 2.4.0后进行了配置读取升级，如果想使用以前的这里设置为true ,注此方法可能不适应高版本
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

  profiles:
    active: dev
    group:
      dev:
        - services
        - gateway
        - resilience4j # 中断器相关配置
        - limit # gateway自带基于redis的限流 ,需要放开pom中的redis限制
        - logger

management:
  endpoint:
    bulkheads:
      enabled: true