server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: route

  cloud:
    gateway:
      routes:
        - id: server-1
          # lb代表从注册中心获取服务
          uri: lb://server-1
          predicates:
            # 转发对外的路径,即: curl http://localhost:8080/hello 实际访问的是内部lb://xc-zookeeper-client/获取的服务
            - Path=/server1/**
          filters:
            # 注意,这个地方是去除前缀,否则会带上/hello去访问注册中心的服务
            - StripPrefix=1